# Generated by Django 3.1.2 on 2020-10-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0002_auto_20201030_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
