# Generated by Django 3.1.2 on 2020-11-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0005_about_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
